version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - QDRANT_URL=${QDRANT_URL}  # Cloud Qdrant URL (replace with actual URL)
      - QDRANT_API_KEY=${QDRANT_API_KEY}  # Cloud Qdrant API Key (replace with actual key)
    depends_on:
      - qdrant  # Remove if using cloud Qdrant

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

  # Remove the qdrant service if using cloud Qdrant
  # qdrant:
  #   build: ./qdrant
  #   ports:
  #     - "6333:6333"
