version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    depends_on:
      - qdrant

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

  qdrant:
    build: ./qdrant
    ports:
      - "6333:6333"
